version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  chroma:
    image: chromadb/chroma:latest
    environment:
      - ALLOW_RESET=true
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"
    restart: always

volumes:
  chroma_data: